wildfly/wildfly-transaction-client

src/main/java/org/wildfly/transaction/TransactionPermission.java, src/main/java/org/wildfly/transaction/client/ContextTransactionManager.java, src/main/java/org/wildfly/transaction/client/LocalUserTransaction.java, src/main/java/org/wildfly/transaction/client/_private/Log.java
This is done because of local transaction invoked in scope of
@Transactional interceptor
(e.g. from Narayana cdi implementation) needs to know if it's fine to
being invoked that context if not exception is thrown.
3.7 Transactional Annotation:
If an attempt is made to call any method of the UserTransaction
interface from within the scope of a bean or method annotated with
@Transactional and a Transactional.TxType other than NOT_SUPPORTED or
NEVER, an IllegalStateException must be thrown.
LocalUserTransaction `setAvailability`/`isAvailable` methods will be called through transactions spi from transaction Narayana cdi interceptor.
=> [WFTC-13] LocalUserTransaction provide methods to set it's availability

src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
Hi @dmlloyd,
I think there is a wrong check in rollback method of JBossLocalTransactionProvider$Entry class.
What I can see from my testing and when looking to the code `rollback` method should change the `if` to `(oldVal & BIT_PREPARE_OR_ROLLBACK) == 0` - meaning throw InvalidStateException when transaction is not in prepared state.
The other changes in this commit are not tested and they came only from my feeling. I would be happy if you can review this PR.
=> Adjusting checks of completionBits from SubordinateTransactionControl

pom.xml, src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
...to exception thrown/serialized to client when transaction fails.
Moving to Narayana spi 7.6.0.Final where ImportedTransaction adds api
method call where suppressed exception could be taken from.
And using Narayana 5.5.24.Final where the api is implemented.
=> [WFTC-9] adding suppressed part of exception

src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
when transient error happens during commiting of imported transaction
https://issues.jboss.org/browse/WFTC-28
=> [WFTC-28] rethrowing XAException with XA_RETRY error code

src/main/java/org/wildfly/transaction/client/_private/Log.java, src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
This is an adjustment of the patch provided for WFTC-25. I think it's not necessary to force running `doRecover` for each transaction which is not found amongst active ones. It should be enough to load transaction from the object store (by running `recover`) once at the start of the container. 
From my testing this change should fix the WFTC-25 in the same manner (at least from the  https://issues.jboss.org/browse/JBEAP-8635 integration point of view).
https://issues.jboss.org/browse/JBEAP-8635
https://issues.jboss.org/browse/WFTC-25
=> [WFTC-25] update with one recovery call after WFTC is started

src/main/java/org/wildfly/transaction/client/provider/remoting/TransactionServerChannel.java
This is a assumption of fixing the https://issues.jboss.org/browse/JBEAP-6156 where `XAER_NOTA` is expected to be thrown in case that remote client tries to commit/prepare/rollback non-existing transaction.
In general here we say that we want to import new transaction, we just tries to find it, if not found we throw the exception.
=> [JBEAP-6156] throwing XAER_NOTA for unknown Xid for XA prepare/commit/rollback

src/main/java/org/wildfly/transaction/client/_private/Log.java, src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
https://issues.jboss.org/browse/WFTC-52
https://developer.jboss.org/message/983112
when subordinate transaction is removed from the 'known' ones, we need to announce Narayana to clean its space too, otherwise there is memory leak happening
@dmlloyd  : I've tried to clean the code a bit while using your advises. Please, check this if it's based on your expectations. I tested it on the 1.1 branch with WFLY13 and from what I can say it works.
Btw. afterwards, will this be expected to be backported to 1.1 branch?
=> [WFTC-52] calling XATerminator when subordinate transaction is removed

src/main/java/org/wildfly/transaction/client/LocalTransaction.java, src/main/java/org/wildfly/transaction/client/_private/Log.java
https://issues.jboss.org/browse/WFTC-54
if `XAResource` is to be enlisted to a transaction that already timeouted then rather throw an exception than continue with the enlistment (see https://issues.jboss.org/browse/WFTC-54?focusedCommentId=13677791#comment-13677791)
This changes the behaviour as the previously the enlistment was permitted and the timeout was changed to value `1` second despite the transaction already timed out.
=> [WFTC-54] forbid to enlist XAResource to a timeouted transaction

src/main/java/org/wildfly/transaction/client/_private/Log.java
https://issues.jboss.org/browse/WFTC-55
Fixing the WARN messages would be marked with id as by standard that all log messages of INFO and higher should generally have message IDs.
/cc @fl4via @dmlloyd @wolfc
=> WFTC-55: Fix for warn log messages to be identified with id

src/main/java/org/wildfly/transaction/client/AbstractTransaction.java
https://issues.jboss.org/browse/WFTC-58
+ adding a test
@dmlloyd: is the test appropriate here for the client. There is no tests so far. Maybe this is too simple and some more "integration" kind of test would be better? Or no test at all?
=> [WFTC-58] getEstimatedTimeout to round down

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
Backporting https://github.com/wildfly/wildfly-transaction-client/pull/71 to 1.1 branch
Jira issue: https://issues.jboss.org/browse/WFTC-60
It supersedes https://github.com/wildfly/wildfly-transaction-client/pull/68
=> [WTC-60] Fix conversion to seconds calculating the SubordinateXAResource transaction remaining timeout

src/main/java/org/wildfly/transaction/client/provider/remoting/TransactionClientChannel.java
...and should be announced as such to transaction manager
https://issues.jboss.org/browse/WFTC-61
https://issues.jboss.org/browse/WFLY-11937
@fl4via @tadamski this fix changes the error codes from `XAER_RMERR` to `XAER_RMFAIL` when `IOException` is received from the remote call. The failed remote call means that the action could be repeated to find out the outcome of the transaction. The `RMERR` defines an un-recoverable error and in such case the transaction is moved to heuristic and operator needs to do manual change.
I did the change not only for the `BlockingInvocation.Response response = invocation.getResponse()` but for the code at `// write rollback-only request`. I think it's correct to be changed there as well but if you can @fl4via take a look to confirm I would be grateful.
=> [WFTC-61] the connection failures are intermittent and should be thrown as RMFAIL

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
https://issues.jboss.org/browse/WFTC-65
When provider for enlistment of XAResource is not available for particular 'uri' NPE should not be thrown.
=> [WFTC-65] (master) no NPE on non-existing provider on resource enlistment

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
https://issues.jboss.org/browse/WFTC-65
master branch PR: https://github.com/wildfly/wildfly-transaction-client/pull/81
When provider for enlistment of `XAResource` is not available for particular 'uri' NPE should not be thrown.
=> [WFTC-65] (1.1) no NPE on non-existing provider on resource enlistment

src/main/java/org/wildfly/transaction/client/provider/remoting/TransactionClientChannel.java
RMFAIL announces to transaction manager that the work could be retried
https://issues.jboss.org/browse/WFTC-61
https://issues.jboss.org/browse/JBEAP-16662
master PR: https://github.com/wildfly/wildfly-transaction-client/pull/73
=> [WFTC-61] (1.0) the connection failures are intermittent and RMFAIL should be used

src/main/java/org/wildfly/transaction/client/provider/remoting/TransactionClientChannel.java
RMFAIL announces to transaction manager that the work could be retried
https://issues.jboss.org/browse/WFTC-61
https://issues.jboss.org/browse/JBEAP-16662
master PR: https://github.com/wildfly/wildfly-transaction-client/pull/73
=> [WFTC-61] (1.1) the connection failures are intermittent and RMFAIL should be used

src/main/java/org/wildfly/transaction/client/provider/jboss/FileSystemXAResourceRegistry.java
Issues: https://issues.jboss.org/browse/WFLY-11357 ,  https://issues.jboss.org/browse/WFTC-53 
PR master: https://github.com/wildfly/wildfly-transaction-client/pull/61
=> [WFLY-11357] add priv block to FileSystemXAResourceRegistry

src/main/java/org/wildfly/transaction/client/provider/jboss/FileSystemXAResourceRegistry.java
Use the file name of the path instead of the full path as the key to remove entry from openFilePaths.
=> WFTC-68 Memory leak in wildfly transaction client

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java, src/main/java/org/wildfly/transaction/client/provider/remoting/TransactionClientChannel.java
https://issues.jboss.org/browse/WFTC-70
1.1 branch PR: https://github.com/wildfly/wildfly-transaction-client/pull/89
This is a regression from fix WFTC-64 where file descriptor is removed
just when no xids are returned. But the XAResource.recover
can be called with different flags and for particular flags
(e.g. `TMENDRSCAN`) no xids are expected to be returned.
The file descriptor can be deleted only when real remote call
is processed which is when `TMSTARTRSCAN` is passed as the flag.
=> [WFTC-70](master)  removing XA file record only on recover start scan

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java, src/main/java/org/wildfly/transaction/client/provider/remoting/TransactionClientChannel.java
https://issues.jboss.org/browse/WFTC-70
master branch PR: https://github.com/wildfly/wildfly-transaction-client/pull/88
This is a regression from fix WFTC-64 where file descriptor is removed
just when no xids are returned. But the XAResource.recover
can be called with different flags and for particular flags
(e.g. `TMENDRSCAN`) no xids are expected to be returned.
The file descriptor can be deleted only when real remote call
is processed which is when `TMSTARTRSCAN` is passed as the flag.
=> [WFTC-70](1.1) removing XA file record only on recover start scan

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
https://issues.jboss.org/browse/WFTC-75
https://issues.jboss.org/browse/JBEAP-17347
@fl4via would you be so kind and review this PR if it's right? What happens is that for failure on XA commit processing the registry does not return the XA resource during recovery. That makes the recovery not deleting the WFTC registry file.
When this will be approved I will create a PR for 1.1 branch. I would need this being fixed for CD18 (aka. JBEAP-17347)
/cc @chengfang
=> [WFTC-75] unfinished XA commit records needs to be recorded for recovery

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
…and not for TMENDRSCAN as well
https://issues.redhat.com/browse/WFTC-82
=> [WFTC-82] XAResourceRegistry is clean only for XAResource.recover TMSTARTSCAN

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
… and not for TMENDRSCAN as well
https://issues.redhat.com/browse/WFTC-82
master PR: https://github.com/wildfly/wildfly-transaction-client/pull/103
=> [WFTC-82] XAResourceRegistry is clean only for XAResource.recover TMSTARTRSCAN

src/main/java/org/wildfly/transaction/client/SimpleXid.java, src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java, src/main/java/org/wildfly/transaction/client/XAOutflowedResources.java, src/main/java/org/wildfly/transaction/client/XAResourceRegistry.java, src/main/java/org/wildfly/transaction/client/XAResourceRegistryProvider.java, src/main/java/org/wildfly/transaction/client/XAResourceRegistryProviderHolder.java, src/main/java/org/wildfly/transaction/client/_private/Log.java, src/main/java/org/wildfly/transaction/client/provider/jboss/FileSystemXAResourceRegistry.java, src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
https://issues.redhat.com/browse/WFTC-85
Finding the cross reference between the registry and the xid of the resource being committed.
I have got an integration test which will be part of WFLY testsuite (https://issues.redhat.com/browse/WFLY-13578)
/CC @fl4via @tadamski
=> [WFTC-85] adding xaregistry register to be used for serialized xa resources

src/main/java/org/wildfly/transaction/client/LocalTransaction.java, src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java, src/main/java/org/wildfly/transaction/client/spi/LocalTransactionProvider.java
The transaction with remote enlistment should be held in memory only for time of `staleTransactionTimeout` after it is being completed.
https://issues.redhat.com/browse/WFTC-86
=> [WFTC-86] finished transaction should be removed from memory mapping

javaee/src/main/java/org/wildfly/transaction/client/_private/Log.java, javaee/src/main/java/org/wildfly/transaction/client/provider/remoting/RemotingRemoteTransactionPeer.java
https://issues.redhat.com/browse/WFTC-93
When CancellationException is thrown, throw XaException.XAER_RMFAIL.
Based on Javadoc for [org.jboss.xnio.IoFuture.get()](https://docs.jboss.org/xnio/1.1/api/org/jboss/xnio/IoFuture.html#get()) method,
it can throw:
- IOException - if the operation failed 
- InterruptedException - if the operation is interrupted 
- CancellationException - if the operation was cancelled
Current code is only able to handle IOException, when "CancellationException" is thrown, this will result on such exception to be thrown back to the Transaction Manager, which is not valid. Only XaException with appropriate error code can be thrown.
=> WFTC-93 RemotingRemoteTransactionPeer#getPeerIdentityXA should handle CancellationException.

pom.xml
https://issues.redhat.com/browse/WFTC-116
=> WFTC-116 parent.relativePath points to the wrong parent pom

pom.xml
https://issues.redhat.com/browse/WFTC-118
this is to port https://github.com/wildfly/wildfly-transaction-client/pull/137 from master branch to 2.x branch.
=> WFTC-118 Upgrade xnio to 3.8.8.Final

src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
https://issues.redhat.com/browse/WFTC-136
=> [WFTC-136] Memory leak, remove XAResourceRecovery when reload

src/main/java/org/wildfly/transaction/client/naming/txn/TxnNamingContext.java, src/main/java/org/wildfly/transaction/client/naming/txn/TxnNamingContextFactory.java
https://issues.redhat.com/browse/WFTC-138
I need this API to proceed with access checking from txn namespace from within WildFly. @chengfang please review.
=> [WFTC-138] Add access checking API to TxnNamingContextFactory

src/main/java/org/wildfly/transaction/client/LocalTransaction.java, src/main/java/org/wildfly/transaction/client/_private/Log.java
https://issues.redhat.com/browse/WFTC-141
=> [WFTC-141] Wildfly-transaction-client doesn't log that the transaction timeout wasn't set, when the driver returns false
