wildfly/wildfly-transaction-client

src/main/java/org/wildfly/transaction/client/provider/remoting/RemotingTransactionServer.java
https://issues.jboss.org/browse/WFTC-23
=> WFTC-23 Add remove transaction method

src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
https://issues.jboss.org/browse/WFTC-25
=> [WFTC-25] reading transaction store when transction is not found in list of active ones

src/main/java/org/wildfly/transaction/client/provider/remoting/TransactionServerChannel.java
https://issues.jboss.org/browse/WFTC-29
https://issues.jboss.org/browse/JBEAP-11081
=> [WFTC-29] not importing transaction when does not exist in before comletion

LICENSE.txt, pom.xml
$unzip -l target/wildfly-transaction-client-1.0.0.CR3-SNAPSHOT.jar 
Archive:  target/wildfly-transaction-client-1.0.0.CR3-SNAPSHOT.jar
Length      Date    Time    Name
---------  ---------- -----   ----
817  07-20-2017 17:32   META-INF/MANIFEST.MF
0  07-20-2017 17:32   META-INF/
0  07-20-2017 17:32   META-INF/services/
0  07-20-2017 17:32   org/
0  07-20-2017 17:32   org/wildfly/
0  07-20-2017 17:32   org/wildfly/transaction/
0  07-20-2017 17:32   org/wildfly/transaction/client/
0  07-20-2017 17:32   org/wildfly/transaction/client/_private/
0  07-20-2017 17:32   org/wildfly/transaction/client/naming/
0  07-20-2017 17:32   org/wildfly/transaction/client/naming/txn/
0  07-20-2017 17:32   org/wildfly/transaction/client/provider/
0  07-20-2017 17:32 …
=> Add licence file and pom information

src/main/java/org/wildfly/transaction/client/RemoteTransaction.java
Jira: https://issues.jboss.org/browse/WFTC-36
=> WFTC-36 Add support for disassociating a remote transaction in limited single-use cases

src/main/java/org/wildfly/transaction/client/_private/Log.java
https://issues.jboss.org/browse/WFTC-55
master PR at: https://github.com/wildfly/wildfly-transaction-client/pull/59
=> WFTC-55: Fix for warn log messages to be identified with id (branch 1.1)

src/main/java/org/wildfly/transaction/client/LocalTransaction.java, src/main/java/org/wildfly/transaction/client/_private/Log.java
https://issues.jboss.org/browse/WFTC-54
https://issues.jboss.org/browse/JBEAP-16089
upstream PR: #63 
backport for branch 1.1 for being released for JBoss EAP 7.2.1, possibly at release 1.1.3
=> WFTC-54 timeouted txn throws exception 1.1.x

src/main/java/org/wildfly/transaction/client/AbstractTransaction.java
A backport of WFTC-58 to branch 1.1.
https://issues.jboss.org/browse/WFTC-58
=> [WFTC-58] getEstimatedTimeout to round down

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
https://issues.jboss.org/browse/WFTC-67
=> [WFTC-67] (master) storing XA repository information until commit or rollback

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
https://issues.jboss.org/browse/WFTC-67
master PR: https://github.com/wildfly/wildfly-transaction-client/pull/82
=> [WFTC-67] (1.1) storing XA repository information until commit or rollback

src/main/java/org/wildfly/transaction/client/provider/jboss/FileSystemXAResourceRegistry.java
Issue: https://issues.jboss.org/browse/WFLY-11357 , https://issues.jboss.org/browse/WFTC-53
=> [WFLY-11357] add priv block to FileSystemXAResourceRegistry

src/main/java/org/wildfly/transaction/client/LocalTransactionContext.java, src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
Jira: https://issues.jboss.org/browse/WFTC-72
=> [WFTC-72] Don't use a global lock

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
https://issues.jboss.org/browse/WFTC-75
https://issues.jboss.org/browse/JBEAP-17347
master PR: https://github.com/wildfly/wildfly-transaction-client/pull/95
=> [WFTC-75] unfinished XA commit records needs to be recorded for further recovery

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
https://issues.jboss.org/browse/WFTC-78
=> [WFTC-78] remove XA registry record when prepare returns read only

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
https://issues.redhat.com/browse/WFTC-77
@tadamski would you be so kind and review this PR? If it's ok from your pow I will create another PR for 1.1 branch then.
=> [WFTC-77] allowing removal of the xa registry file on Narayana bottom-up

src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java
https://issues.redhat.com/browse/WFTC-77
master PR: https://github.com/wildfly/wildfly-transaction-client/pull/99
=> [WFTC-77] allow deletion on bottom up 1.1

src/main/java/org/wildfly/transaction/client/naming/txn/TxnNamingContext.java
https://issues.redhat.com/browse/WFTC-81
=> [WFTC-81] always use RemoteUserTransaction for txn:UserTransaction

src/main/java/org/wildfly/transaction/client/SimpleXid.java, src/main/java/org/wildfly/transaction/client/SubordinateXAResource.java, src/main/java/org/wildfly/transaction/client/XAOutflowedResources.java, src/main/java/org/wildfly/transaction/client/XAResourceRegistry.java, src/main/java/org/wildfly/transaction/client/XAResourceRegistryProvider.java, src/main/java/org/wildfly/transaction/client/XAResourceRegistryProviderHolder.java, src/main/java/org/wildfly/transaction/client/_private/Log.java, src/main/java/org/wildfly/transaction/client/provider/jboss/FileSystemXAResourceRegistry.java, src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
https://issues.redhat.com/browse/WFTC-85
upstream pr: https://github.com/wildfly/wildfly-transaction-client/pull/106
=> [WFTC-85] adding xaregistry register to be used for serialized xaresources

src/main/java/org/wildfly/transaction/client/provider/jboss/JBossJTALocalTransactionProvider.java
https://issues.redhat.com/browse/WFTC-90
=> [WFTC-90] do not throw NPE on disabled transactions

src/main/java/org/wildfly/transaction/client/_private/Log.java, src/main/java/org/wildfly/transaction/client/provider/remoting/RemotingRemoteTransactionPeer.java
Issue: https://issues.redhat.com/browse/WFTC-93
master branch PR: [#115 ](https://github.com/wildfly/wildfly-transaction-client/pull/115)
=> [WFTC-93] (JBEAP-22076) RemotingRemoteTransactionPeer#getPeerIdentityXA should handle CancellationException

pom.xml
https://issues.redhat.com/browse/WFTC-104
=> [WFTC-104] Upgrading WildFly Naming Client to 2.0.0.Final version

pom.xml
https://issues.redhat.com/browse/WFTC-111
=> WFTC-111 Upgrade jakarta.transaction-api from 2.0.0 to 2.0.1

.github/workflows/ejb-client.yml
https://issues.redhat.com/browse/WFTC-110
=> WFTC-110 Add github action to test with jboss-ejb-client

.github/workflows/ci.yml
https://issues.redhat.com/browse/WFTC-117
=> WFTC-117 Upgrade github actions to avoid github action warnings

pom.xml
https://issues.redhat.com/browse/WFTC-118
=> WFTC-118 Upgrade xnio to 3.8.8.Final

pom.xml
Addresses [WFTC-119](https://issues.redhat.com/browse/WFTC-119)
=> [WFTC-119] Updated Narayana and its SPI to native jakarta

.github/dependabot.yml
https://issues.redhat.com/browse/WFTC-121
=> WFTC-121 Enable github dependabot

pom.xml, src/test/java/org/wildfly/transaction/client/DummyServer.java, src/test/java/org/wildfly/transaction/client/LocalUserTransactionTestCase.java, src/test/java/org/wildfly/transaction/client/RemoteUserTransactionTestCase.java, src/test/java/org/wildfly/transaction/client/provider/jboss/TestExtendedJBossXATerminator.java, src/test/java/org/wildfly/transaction/client/provider/jboss/TestImportedTransaction.java, src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransaction.java, src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransactionManager.java, src/test/java/org/wildfly/transaction/client/provider/jboss/TestTransactionProvider.java, src/test/java/org/wildfly/transaction/client/provider/jboss/TestXAResource.java, src/test/java/org/wildfly/transaction/client/provider/jboss/TestXAResourceRecoveryRegistry.java, src/test/java/org/wildfly/transaction/client/provider/jboss/TestXid.java, src/test/resources/org/wildfly/transaction/client/RemoteUserTransactionTestCase.btm
https://issues.redhat.com/browse/WFTC-108
=> [WFTC-108] Unit tests draft

docs/src/main/asciidoc/community-documentation.adoc, pom.xml
This PR will contain the initial version of the wildfly-transaction-client documentation.
It is in draft state and will be added to until ready for becoming a valid PR.
=> Initial docs setup

.github/workflows/ci.yml, .github/workflows/ejb-client.yml, .github/workflows/wildfly.yml
https://issues.redhat.com/browse/WFTC-128
=> WFTC-128 Increase the CI timeout and other cleanup

src/test/java/org/wildfly/transaction/client/RemoteUserTransactionTestCase.java
https://issues.redhat.com/browse/WFTC-129
=> WFTC-129 RemoteUserTransactionTestCase test failures on JDK 17 windows

pom.xml
https://issues.redhat.com/browse/WFTC-131
=> WFTC-131 Upgrade metainf-services from 1.7 to 1.11

.github/workflows/ci-manual.yml
https://issues.redhat.com/browse/WFTC-132
=> WFTC-132 Enable manual start of github actions CI workflow [skip ci]

pom.xml
https://issues.redhat.com/browse/WFTC-133
=> WFTC-133 Add JBoss Public Repository Group to project maven settings in pom.xml

.github/workflows/ci-manual.yml, .github/workflows/ci.yml
https://issues.redhat.com/browse/WFTC-134
=> WFTC-134 Use github workflow cache action to speed up ci run

src/main/java/org/wildfly/transaction/client/provider/jboss/JBossLocalTransactionProvider.java
https://issues.redhat.com/browse/WFTC-136
Port the fix from main to 1.1 branch: #172
=> [WFTC-136] Memory leak, remove XAResourceRecovery when reload (#172)

src/main/java/org/wildfly/transaction/client/_private/Log.java
https://issues.redhat.com/browse/WFTC-142
=> [WFTC-142] Lower logging level to debug for transaction timeout
